workflows:
ios-upload:
name: iOS Upload
environment:
vars:
APP_STORE_CONNECT_ISSUER_ID: $APP_STORE_CONNECT_ISSUER_ID
APP_STORE_CONNECT_KEY_IDENTIFIER: $APP_STORE_CONNECT_KEY_IDENTIFIER
APP_STORE_CONNECT_PRIVATE_KEY: $APP_STORE_CONNECT_PRIVATE_KEY
scripts:
- name: Download IPA from Google Drive
script: |
curl -L -o app.ipa "https://drive.google.com/uc?export=download&id=1tWp4wRAHNiCOp204B1EM9ypj_FwG2AHP"
- name: Upload IPA to App Store Connect
script: |
xcrun altool --upload-app -f app.ipa -t ios \
--apiKey $APP_STORE_CONNECT_KEY_IDENTIFIER \
--apiIssuer $APP_STORE_CONNECT_ISSUER_ID \
--apiKeyFile <(echo "$APP_STORE_CONNECT_PRIVATE_KEY")
