workflows:
ios-upload:
ios-distribute:
name: iOS Distribute
environment:
vars:
APPLE_ID: "scrapzoneglobal@gmail.com"
APP_SPECIFIC_PASSWORD: Encrypted(********)
scripts:
- echo "Using Apple ID authentication"
publishing:
app_store_connect:
apple_id: $APPLE_ID
password: $APP_SPECIFIC_PASSWORD
